# Site settings
title: FlatIron 
header-img: img/home-bg.png
email: khitx@icloud.com
copyright_name: khitx
description: > # this means to ignore newlines until "baseurl:"
  Community-Powered Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  khitx
learn_profile: khitx
email_username: khitx@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
